cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

foodies1/urls.py
# from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    # path('admin/', admin.site.urls),
    # path('cart/', include('cart.urls', namespace='cart')),
    path('', include('foodiesapp.urls')),

]

foodiesapp/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    # path('', views.index_contact, name='index_contact'),
    path('breakfast/', views.breakfast, name='breakfast'),
    path('lunch/', views.lunch, name='lunch'),
    path('burger/', views.burger, name='burger'),
    path('kolaches/', views.kolaches, name='kolaches'),
    path('cookies/', views.cookies, name='cookies'),
    path('bread/', views.bread, name='bread'),
    path('gelato/', views.gelato, name='gelato'),
    path('coffee/', views.coffee, name='coffee'),
    path('about/', views.about, name='about'),
    path('contact/', views.contact, name='contact'),

]

cart/models.py
from django.db import models

# Create your models here.

foodiesapp/models.py
from django.db import models





# Create your models here.
# class Category(models.Model):
#     name = models.CharField(max_length=200, db_index=True)
#     slug = models.SlugField(max_length=200, db_index=True, unique=True)

#     class Meta:
#         ordering = ('name',)
#         verbose_name = 'category'
#         verbose_name_plural = 'categories'

#     def __str__(self):
#         return self.name

# class Product(models.Model):
#     category = models.ForeignKey(Category, related_name='products', on_delete=models.CASCADE)
#     name = models.CharField(max_length=200, db_index=True)
#     slug = models.SlugField(max_length=200, db_index=True)
#     # image = models.SlugField(upload_to='products/YY/MM/DD', blank=True)
#     description = models.TextField(blank=True)
#     price = models.DecimalField(max_digits=10, decimal_places=2)
#     stock = models.PositiveIntegerField()
#     available = models.BooleanField(default=True)
#     created = models.DateTimeField(auto_now_add=True)
#     updated = models.DateTimeField(auto_now=True)

# class Meta:
#     ordering = ('-created',)
#     index_together = (('id', 'slug'),)

# def __str__(self):
#     return self.name

cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]

class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int)
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
# from foodiesapp.models import Product
from .cart import Cart
from .forms import CartAddProductForm

# Create your views here.
@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product,
                 quantity=cd['quantity'],
                 update_quantity=cd['update'])
    return redirect('cart:cart_detail')


def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')


def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(initial={'quantity': item['quantity'],
                                                                   'update': True})
    return render(request, 'cart/detail.html', {'cart': cart})

foodiesapp/views.py
from django.shortcuts import render, redirect
# from .models import Category, Product
# from cart.forms import CartAddProductForm


def index(request):
    return render(request,'foodiesapp/index.html')

# def index_contact(request):
#     return render(request,'foodiesapp/index.html')

def breakfast(request):
    return render(request, 'foodiesapp/breakfast.html')

def lunch(request):
    return render(request, 'foodiesapp/lunch.html')

def burger(request):
    return render(request, 'foodiesapp/burger.html')

def kolaches(request):
    return render(request, 'foodiesapp/kolaches.html')

def cookies(request):
    return render(request, 'foodiesapp/cookies.html')

def bread(request):
    return render(request, 'foodiesapp/bread.html')

def gelato(request):
    return render(request, 'foodiesapp/gelato.html')

def coffee(request):
    return render(request, 'foodiesapp/coffee.html')

def about(request):
    return render(request, 'foodiesapp/about.html')

def contact(request):
    return render(request, 'foodiesapp/contact.html')


# def product_list(request, category_slug=None):
#     category = None
#     categories = Category.object.all()
#     products = Product.filter(available=True)
#     if category_slug:
#         category = get_object_or_404(Category, slug=category_slug)
#         products = products.filter(category=category)
#     return render(request, 'foodiesapp/product/list.html', {'category': category,
#                                                       'categories': categories,
#                                                       'products': products})

# def product_detail(request, id, slug):
#     product = get_object_or_404(Product, id=id, slug=slug, available=True)
#     cart_product_form = CartAddProductForm()
#     return render(request,
#                   'foodiesapp/product/detail.html',
#                   ('product': product,
#                   'cart_product_form': cart_product_form))

cart/templates/cart/detail.html
{% extends "foodiesapp/base.html" %}
{% load static %}

{% block title %}
    Your cart
{% endblock %}

{% block content %}
    <h1>Your cart</h1>
    <table class="cart">
        <thead>
            <tr>
                <th>Image</th>
                <th>Product</th>
                <th>Quantity</th>
                <th>Remove</th>
                <th>Unit price</th>                
                <th>Price</th>
            </tr>
        </thead>
        <tbody>
        {% for item in cart %}
            {% with product=item.product %}
            <tr>
                <td>
                    <a href="{{ product.get_absolute_url }}">
                        <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static "shop/no_image.png" %}{% endif %}">
                    </a>
                </td>
                <td>{{ product.name }}</td>
                <td>
                    <form action="{% url "cart:cart_add" product.id %}" method="post">
                        {{ item.update_quantity_form.quantity }}
                        {{ item.update_quantity_form.update }}
                        <input type="submit" value="Update">
                        {% csrf_token %}
                    </form>
                </td>
                <td><a href="{% url "cart:cart_remove" product.id %}">Remove</a></td>
                <td class="num">${{ item.price }}</td>
                <td class="num">${{ item.total_price }}</td>
            </tr>
            {% endwith %}
        {% endfor %}
        <tr class="total">
            <td>Total</td>
            <td colspan="4"></td>
            <td class="num">${{ cart.get_total_price }}</td>
        </tr>
        </tbody>
    </table>
    <p class="text-right">
        <a href="{% url "shop:product_list" %}" class="button light">Continue shopping</a>

    </p>
{% endblock %}

foodiesapp/templates/foodiesapp/about.html
{% extends 'foodiesapp/base.html' %}
{% load static %}


{% block content %}

<!-- Start About -->
<section id="gallery" class="templatemo-section">
<h2 id="about" class="text-center text-uppercase">About Us</h2>
<br>
<div class="body-style">
    Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of "de Finibus Bonorum et Malorum" (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, "Lorem ipsum dolor sit amet..", comes from a line in section 1.10.32.
</div>
</section>
<!-- End About -->

{% endblock %}

foodiesapp/templates/foodiesapp/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0, viewport-fit=cover"> 
    <!-- <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"> -->

	<title>Foodies</title>
	<!-- add icon link -->
    <link rel = "icon" href = "{% static 'foodiesapp/images/menubar.jpg' %}" type = "image/x-icon"> 
	
	<meta http-equiv="X-UA-Compatible" content="IE=Edge">
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0 viewport-fit=cover">

	<!-- bootstrap -->
	<link rel="stylesheet" href="{% static 'foodiesapp/css/bootstrap.min.css' %}">
	
	<!-- font-awesome -->
	<link rel="stylesheet" href="{% static 'foodiesapp/css/font-awesome.min.css' %}">
	<!-- custom -->
    <link rel="stylesheet" type="text/css" href="{% static 'foodiesapp/css/style.css' %}">
    
    <!-- js -->


	<!-- google font -->
	<link href='//fonts.googleapis.com/css?family=Signika:400,300,600,700' rel='stylesheet' type='text/css'>
	<link href='//fonts.googleapis.com/css?family=Chewy' rel='stylesheet' type='text/css'>

</head>
<body id="home" data-spy="scroll" data-target=".navbar-collapse">

	<!-- start navigation -->
	<div class="navbar navbar-default navbar-fixed-top" role="navigation">
		<div class="container">
			<div class="navbar-header">
				<button class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
					<span class="icon icon-bar"></span>
					<span class="icon icon-bar"></span>
					<span class="icon icon-bar"></span>
				</button>
				<a href="#home" class="navbar-brand smoothScroll"><img class="logoimg" src="{% static 'foodiesapp/images/logo.jpg' %}" alt="logo.jpg"></a>
			</div>
			<div class="collapse navbar-collapse" id="main_nav">
				<ul class="nav navbar-nav navbar-right">
					<li class="nav-item"><a class="nav-link" href="{% url 'index' %}">HOME</a></li>
					<!-- <li class="nav-item"><a class="nav-link" href="{% url 'about' %}">ABOUT</a></li> -->
					<li class="nav-item dropdown">
						<a class="nav-link dropdown-toggle" href="#Menu" id="navbarDropdown" role="button" data-toggle="dropdown">MENU ▾</a>
						<ul class="dropdown-menu">
							<li class="newcursr"><a class="dropdown-toggle"> Fresh Deli &raquo</a>
								<ul class=" submenu dropdown-menu">
									<li><a class="dropdown-item" href="{% url 'breakfast' %}">Breakfast</a></li>
									<li><a class="dropdown-item" href="{% url 'lunch' %}">Lunch</a></li>
									<li><a class="dropdown-item" href="{% url 'burger' %}">Burger</a></li>
								</ul>
							</li>
							<li class="newcursr"><a class="dropdown-toggle"> Bakery &raquo</a>
								<ul class="submenu dropdown-menu">
									<li><a class="dropdown-item" href="{% url 'kolaches' %}">Kolaches</a></li>
									<li><a class="dropdown-item" href="{% url 'cookies' %}">Cookies</a></li>
									<li><a class="dropdown-item" href="{% url 'bread' %}">Bread</a></li>
								</ul>
							</li>
							<li><a class="dropdown-item" href="{% url 'gelato' %}">Gelato</a></li>
							<li><a class="dropdown-item" href="{% url 'coffee' %}">Coffee</a></li>
						</ul>
					</li> 
					<li><a href="{% url 'contact' %}">CONTACT</a></li>						
					<!-- <a href="javascript:void(0);" class="icon" onclick="myFunction()"></a> -->
				</ul>
			</div>
		</div>
	</div>
	<!-- end navigation -->

	<main>
		{% block content %}
		
        {% endblock %}
    </main>

	<!-- start footer -->
	<!-- <footer>
		<div class="container">
			<div class="row">
				<div class="col-md-12">
					<p>Copyright &copy; foodies</p>
					<hr>
				</div>
			</div>
		</div>
	</footer> -->
	<!-- end footer -->


	<script src="{% static 'foodiesapp/js/jquery.js' %}"></script>
	<script src="{% static 'foodiesapp/js/bootstrap.min.js' %}"></script>
	<script src="{% static 'foodiesapp/js/plugins.js' %}"></script>
	<script src="{% static 'foodiesapp/js/smoothscroll.js' %}"></script>
	<script src="{% static 'foodiesapp/js/custom.js' %}"></script>

</body>
</html>

foodiesapp/templates/foodiesapp/bread.html
{% extends 'foodiesapp/base.html' %}
{% load static %}

{% block content %}

    <!-- Start Body Section -->
    <section id="gallery" class="templatemo-section">
		<div class="container">
			<div class="row">
				<div class="weikels">
					<img src="{% static 'foodiesapp/images/weikels.jpg' %}">
					<div class="weikels"> 
						<img src="{% static 'foodiesapp/images/weikels_logo.jpg' %}" class="weikelslogo">
					</div>					<!-- <div class="contact">
						<p>ruhip@gmail.com</p>
						<p>5125674612</p>
					</div> -->
				</div>
				<br>
				<div class="col-md-12">
					<h2 class="text-center text-uppercase">Breads</h2>
					<hr>
				</div> 
				<div class="col-md-4 col-sm-4">
					<div class="gallery-wrapper">
						<img src="{% static 'foodiesapp/images/bread1.jpg' %}" class="img-responsive gallery-img" alt="Kolaches 1">
						<div class="gallery-des3">
							<h4 class="kolaches">White Sliced-Regular </h4>
							<h5 class="kolaches">Single&nbsp;(Loaf)&nbsp;&nbsp;&nbsp; $3.25</h5>
						</div>
					</div>
				</div>	
				<div class="col-md-4 col-sm-4">
					<div class="gallery-wrapper">
						<img src="{% static 'foodiesapp/images/bread2.jpg' %}" class="img-responsive gallery-img" alt="Kolaches 2">
						<div class="gallery-des3">
                            <h4 class="kolaches">White Sliced-Thin </h4>
							<h5 class="kolaches">Single&nbsp;(Loaf)&nbsp;&nbsp;&nbsp; $3.25</h5>
						</div>
					</div>
                </div>
                <div class="col-md-4 col-sm-4">
					<div class="gallery-wrapper">
						<img src="{% static 'foodiesapp/images/bread3.jpg' %}" class="img-responsive gallery-img" alt="Kolaches 4">
						<div class="gallery-des2">
							<h4 class="kolaches">White Unsliced </h4>
							<h5 class="kolaches">Single&nbsp;(Loaf)&nbsp;&nbsp;&nbsp; $3.25</h5>
						</div>
					</div>
                </div>
                <div class="col-md-4 col-sm-4">
					<div class="gallery-wrapper">
						<img src="{% static 'foodiesapp/images/bread4.jpg' %}" class="img-responsive gallery-img" alt="Kolaches 4">
						<div class="gallery-des3">
							<h4 class="kolaches">Wheat Sliced-Regular </h4>
							<h5 class="kolaches">Single&nbsp;(Loaf)&nbsp;&nbsp;&nbsp; $3.25</h5>
						</div>
					</div>
                </div>
                <div class="col-md-4 col-sm-4">
					<div class="gallery-wrapper">
						<img src="{% static 'foodiesapp/images/bread5.jpg' %}" class="img-responsive gallery-img" alt="Kolaches 4">
						<div class="gallery-des3">
							<h4 class="kolaches">Wheat Sliced-Thin </h4>
							<h5 class="kolaches">Single&nbsp;(Loaf)&nbsp;&nbsp;&nbsp; $3.25</h5>
						</div>
					</div>
				</div>
				<div class="col-md-4 col-sm-4">
					<div class="gallery-wrapper">
						<img src="{% static 'foodiesapp/images/bread6.jpg' %}" class="img-responsive gallery-img" alt="Kolaches 3">
						<div class="gallery-des3">
                            <h4 class="kolaches">Wheat Unsliced </h4>
							<h5 class="kolaches">Single&nbsp;(Loaf)&nbsp;&nbsp;&nbsp; $3.25</h5>
						</div>
					</div>
                </div>
			</div>
		</div>
	</section>
    <!-- End Body Section -->

{% endblock %}

foodiesapp/templates/foodiesapp/breakfast.html
{% extends 'foodiesapp/base.html' %}
{% load static %}

{% block content %}
<!-- Start Body Section -->
<section id="gallery" class="templatemo-section">
    <div class="container">
        <div class="row">
            <div class="col-md-12">                   
                <h2 class="text-center text-uppercase">Breakfast</h2>
                <h4 class="text-center">Fresh! Make your own!</h3>
            </div>
            <hr>
        </div>
        <h3 class="t_toast">Tacos & Burritos</h3>
        <br>
        <div class="row">
            <div class="col-sm-6">
                    <img class="icon1" src="{% static 'foodiesapp/images/taco.jpg' %}">
                    <div class="gallery-des6">
                        <h4 class="kolaches">$1.99 </h4>&nbsp;&nbsp;&nbsp;
                        <h5 class="kolaches">(each) </h5>
                    </div>
            </div>
            <div class="col-sm-6">
                    <img class="icon1" src="{% static 'foodiesapp/images/burrito.jpg' %}">
                    <div class="gallery-des6">
                        <h4 class="kolaches">$3.99 </h4>&nbsp;&nbsp;&nbsp;
                        <h5 class="kolaches">(each) </h5>
                    </div>
                </div>
        </div>
        <div class="row">
            <div class="col-sm-12">
                <div class="breakfast">
                    <h4 class="kolaches">Bacon, Egg, n Cheese </h4>
                    <h4 class="kolaches">Potato, Egg, n Cheese </h4>
                    <h4 class="kolaches">Sausage, Egg, n Cheese </h4>
                    <h4 class="kolaches">Chorizo, Egg, n Cheese </h4>
                </div>
            </div>
        </div>
        <hr>
        <br>
        <h3 class="t_toast">Texas Toast</h3>
        <br>
        <div class="row">
            <div class="col-sm-12">
                <div class="breakfast">
                    <img class="icon1" src="{% static 'foodiesapp/images/toast.jpg' %}">
                    <div class="gallery-des7">
                        <h4 class="kolaches">$2.99</h4>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-12">
                <div class="breakfast">
                    <h4 class="kolaches">Bacon, Egg, n Cheese </h4>
                    <h4 class="kolaches">Ham, Egg, n Cheese </h4>
                    <h4 class="kolaches">Sausage, Egg, n Cheese </h4>
                </div>
                <br><br><br>
                <div>
                    <div class="breakfast">
                        <h4 class="kolaches">Add extra bacon for $1 | * Any ingredient will be extra * </h4>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- End Body Section -->

{% endblock %}

foodiesapp/templates/foodiesapp/burger.html
{% extends 'foodiesapp/base.html' %}
{% load static %}

{% block content %}

    <!-- Start Body Section -->
    <section id="gallery" class="templatemo-section">
		<div class="container">
			<div class="row">
				<div class="col-md-12">
                    
                    <h2 class="text-center text-uppercase">Burgers</h2>
                    <!-- <hr> -->
					<h4 class="text-center">Fresh made hand patties!</h3>
                    <hr>
                    <br><br><br>
				</div> 
				<div class="col-md-12 ">
					<div class="gallery-wrapper">
						<img class="icon" src="{% static 'foodiesapp/images/iconeimg.jpg' %}">
						<div class="gallery-icon">
							<h4 class="kolaches">Combo Includes </h4>
							<h2 class="icon-wrt">Fries & Drink</h2>
							<h5 class="kolaches">Upto 32oz</h5>
						</div>
					</div>
				</div>
				<div class="col-md-4 col-sm-4">
					<div class="gallery-wrapper">
						<img src="{% static 'foodiesapp/images/burger1.jpg' %}" class="img-responsive gallery-img" alt="Kolaches 1">
						<div class="gallery-des3">
							<h4 class="kolaches">Hambuger </h4>
							<h5 class="kolaches">Combo &nbsp;&nbsp;&nbsp; $6.99</h5>
							<h5 class="kolaches">Single &nbsp;&nbsp;&nbsp; $4.99</h5>
						</div>
					</div>
				</div>	
				<div class="col-md-4 col-sm-4">
					<div class="gallery-wrapper">
						<img src="{% static 'foodiesapp/images/burger2.jpg' %}" class="img-responsive gallery-img" alt="Kolaches 2">
						<div class="gallery-des3">
                            <h4 class="kolaches">Double Meat</h4>
							<h5 class="kolaches">Combo &nbsp;&nbsp;&nbsp; $8.99</h5>
							<h5 class="kolaches">Single &nbsp;&nbsp;&nbsp; $6.99</h5>
						</div>
					</div>
				</div>
                <div class="col-md-4 col-sm-4">
					<div class="gallery-wrapper">
						<img src="{% static 'foodiesapp/images/burger3.jpg' %}" class="img-responsive gallery-img" alt="Kolaches 4">
						<div class="gallery-des3">
							<h4 class="kolaches">Habenero Burger</h4>
							<h5 class="kolaches">Combo &nbsp;&nbsp;&nbsp; $7.99</h5>
							<h5 class="kolaches">Single &nbsp;&nbsp;&nbsp; $5.99</h5>
						</div>
					</div>
				</div>
                <div class="col-md-4 col-sm-4">
					<div class="gallery-wrapper">
						<img src="{% static 'foodiesapp/images/burger4.jpg' %}" class="img-responsive gallery-img" alt="Kolaches 4">
						<div class="gallery-des3">
							<h4 class="kolaches">Bacon Burger</h4>
							<h5 class="kolaches">Combo &nbsp;&nbsp;&nbsp; $8.99</h5>
							<h5 class="kolaches">Single &nbsp;&nbsp;&nbsp; $6.99</h5>
						</div>
					</div>
				</div>
                <div class="col-md-4 col-sm-4">
					<div class="gallery-wrapper">
						<img src="{% static 'foodiesapp/images/burger5.jpg' %}" class="img-responsive gallery-img" alt="Kolaches 4">
						<div class="gallery-des3">
							<h4 class="kolaches">Philly Steak</h4>
							<h5 class="kolaches">Combo &nbsp;&nbsp;&nbsp; $7.99</h5>
							<h5 class="kolaches">Single &nbsp;&nbsp;&nbsp; $5.99</h5>
						</div>
					</div>
				</div>
				<div class="col-md-4 col-sm-4">
					<div class="gallery-wrapper">
						<img src="{% static 'foodiesapp/images/fries.jpg' %}" class="img-responsive gallery-img" alt="Kolaches 3">
						<div class="gallery-des3">
                            <h4 class="kolaches">Fries only</h4>
							<h5 class="kolaches">$1.79</h5>
							<br>
						</div>
					</div>
                </div>
			</div>
		</div>
	</section>
    <!-- End Body Section -->


{% endblock %}

foodiesapp/templates/foodiesapp/contact.html
{% extends 'foodiesapp/index.html' %}
{% load static %}


{% block content %}

<!-- Start contact form in use -->
<div id="contact" class="templatemo-section">
	<section id="gallery" class="text-center text-uppercase">
		<h2 class="newcont">Contact &nbsp;Information</h2>
		<section class="alt">
			<h3>Phone</h3>
			<p>(512) 568-4619</p>
		</section>
		<section class="alt">
			<h3>Email</h3>
			<p>ruhiprasla94@gmail.com</p>
        </section>
        <section class="alt">
			<h3>Address</h3>
			<p>11340 TX-183A Toll Rd Leander, TX 78641</p>
        </section>
        <section class="alt">
			<h3>Hours</h3>
			<p>24 hours</p>
		</section>
    </section>
    <br><br><br>
    <div class="map-responsive" class="mapouter">
        <div class="gmap_canvas">
            <iframe width="564" height="409" id="gmap_canvas" src="https://maps.google.com/maps?q=foodies%20corner&t=&z=11&ie=UTF8&iwloc=&output=embed" frameborder="0" scrolling="no" marginheight="0" marginwidth="0"></iframe>
        </div>
    </div>
</div>
<!-- end contact for in use -->

{% endblock %}

foodiesapp/templates/foodiesapp/gelato.html
{% extends 'foodiesapp/base.html' %}
{% load static %}

{% block content %}

    <!-- Start Body Section -->
    <section id="gallery" class="templatemo-section">
		<div class="container">
			<div class="row">
				<div class="col-md-12">
					<h2 class="text-center text-uppercase">Gelato</h2>
					<hr>
				</div> 
				<div class="col-md-4 col-sm-4">
					<div class="gallery-wrapper">
						<img src="{% static 'foodiesapp/images/gelato1.jpg' %}" class="img-responsive gallery-img" alt="Kolaches 1">
						<div class="gallery-des3">
							<h4 class="kolaches">Chocolate Gelato </h4>
							<h5 class="kolaches">Single &nbsp;&nbsp;&nbsp; $5.99</h5>
						</div>
					</div>
				</div>	
				<div class="col-md-4 col-sm-4">
					<div class="gallery-wrapper">
						<img src="{% static 'foodiesapp/images/gelato2.jpg' %}" class="img-responsive gallery-img" alt="Kolaches 2">
						<div class="gallery-des3">
                            <h4 class="kolaches">Vanilla Gelato </h4>
							<h5 class="kolaches">Single &nbsp;&nbsp;&nbsp; $5.99</h5>
						</div>
					</div>
                </div>
                <div class="col-md-4 col-sm-4">
					<div class="gallery-wrapper">
						<img src="{% static 'foodiesapp/images/gelato3.jpg' %}" class="img-responsive gallery-img" alt="Kolaches 4">
						<div class="gallery-des2">
							<h4 class="kolaches">Strawberry Gelato </h4>
							<h5 class="kolaches">Single &nbsp;&nbsp;&nbsp; $5.99</h5>
						</div>
					</div>
                </div>
                <div class="col-md-4 col-sm-4">
					<div class="gallery-wrapper">
						<img src="{% static 'foodiesapp/images/gelato4.jpg' %}" class="img-responsive gallery-img" alt="Kolaches 4">
						<div class="gallery-des3">
							<h4 class="kolaches">Cookies & Cream Gelato </h4>
							<h5 class="kolaches">Single &nbsp;&nbsp;&nbsp; $5.99</h5>
						</div>
					</div>
                </div>
                <div class="col-md-4 col-sm-4">
					<div class="gallery-wrapper">
						<img src="{% static 'foodiesapp/images/gelato5.jpg' %}" class="img-responsive gallery-img" alt="Kolaches 4">
						<div class="gallery-des3">
							<h4 class="kolaches">Expresso Gelato </h4>
							<h5 class="kolaches">Single &nbsp;&nbsp;&nbsp; $5.99</h5>
						</div>
					</div>
				</div>
				<div class="col-md-4 col-sm-4">
					<div class="gallery-wrapper">
						<img src="{% static 'foodiesapp/images/gelato6.jpg' %}" class="img-responsive gallery-img" alt="Kolaches 3">
						<div class="gallery-des3">
                            <h4 class="kolaches">Mango Gelato</h4>
							<h5 class="kolaches">Single &nbsp;&nbsp;&nbsp; $5.99</h5>
						</div>
					</div>
                </div>
			</div>
		</div>
	</section>
    <!-- End Body Section -->

{% endblock %}